version : "3.8"

service:
    app:
        build:
            context:
        container_name : "rously/dockercraft"
                
        ports:
            -   "80:8501"
        volumes:
            -   ./:/app

            
            